// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnionFlSNcIFonjWyB8C8cYJQd6jVzAG8',
    appId: '1:910160791026:web:f30267d60e0ba7155f576b',
    messagingSenderId: '910160791026',
    projectId: 'tourism-app-5f40d',
    authDomain: 'tourism-app-5f40d.firebaseapp.com',
    storageBucket: 'tourism-app-5f40d.firebasestorage.app',
    measurementId: 'G-DCDWZCK4ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmkjEfwOAhHdqK1_M18tnGv6XHAQdJ0Y',
    appId: '1:910160791026:android:81ec63ce26e1d91e5f576b',
    messagingSenderId: '910160791026',
    projectId: 'tourism-app-5f40d',
    storageBucket: 'tourism-app-5f40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmybLQNhIiJKLhr-iER6DTxNWLcrkx4Pg',
    appId: '1:910160791026:ios:e79b4d17890dea305f576b',
    messagingSenderId: '910160791026',
    projectId: 'tourism-app-5f40d',
    storageBucket: 'tourism-app-5f40d.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );
}
